name: Build Frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: playlist-sync-frontend

      - name: Build frontend
        run: npm run build
        working-directory: playlist-sync-frontend

      - name: Verify build output
        run: |
          if [ ! -d "playlist-sync-frontend/build" ]; then
            echo "Build folder not found!"
            exit 1
          fi